#
#Fri Aug 13 19:08:20 CEST 2010
USE_PLUGINS=
EDLRULES=$EDLRULES_DIR$/edlValidation_rules.xml
XSD=$XSD_DIR$/rtExperiment_v14.xsd
DOCUMENTELEMENT=rtExperiment
LOGGER_CONFIGURATION=$CONFIG_DIR$/logger.conf
